# Generated by Django 3.2 on 2022-03-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20220318_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('joining_date', models.DateField(null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('total_leave', models.IntegerField(blank=True, null=True)),
                ('remaining_leave', models.IntegerField(blank=True, null=True)),
                ('profile_type', models.CharField(choices=[('general', 'general'), ('manager', 'manager'), ('hr', 'hr')], default='general', max_length=20)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('passport_or_nid', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('emergency_phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
