# Generated by Django 3.2 on 2022-03-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220326_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('annual', 'annual'), ('sick', 'sick'), ('others', 'others')], default='annual', max_length=10)),
                ('total_day_count', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kpi_year', models.IntegerField()),
                ('status', models.CharField(choices=[('manager', 'manager'), ('ongoing', 'ongoing'), ('review', 'review'), ('started', 'started'), ('completed', 'completed')], default='started', max_length=20)),
                ('goal', models.CharField(max_length=250)),
                ('weightage', models.CharField(max_length=100)),
                ('l2', models.CharField(blank=True, max_length=50, null=True)),
                ('l3', models.CharField(blank=True, max_length=50, null=True)),
                ('l4', models.CharField(blank=True, max_length=50, null=True)),
                ('l5', models.CharField(blank=True, max_length=50, null=True)),
                ('self_rating', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='api.employee')),
            ],
        ),
    ]
