# Generated by Django 3.2 on 2022-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_kpi_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_type',
            field=models.CharField(choices=[('general', 'general'), ('hr', 'hr')], default='general', max_length=20),
        ),
    ]
