# Generated by Django 3.2 on 2022-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220330_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='status',
            field=models.CharField(choices=[('manager', 'manager'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='ongoing', max_length=20),
        ),
    ]
