# Generated by Django 3.2 on 2022-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220330_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
