# Generated by Django 3.2 on 2022-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
