# Generated by Django 3.2 on 2022-08-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220817_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user_id',
        ),
    ]
