# Generated by Django 3.2 on 2022-08-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_attendance_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='department',
            new_name='lastdate',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated',
        ),
    ]
