# Generated by Django 3.2 on 2022-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220817_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
