# Generated by Django 3.2 on 2022-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_attendance_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='terminal_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='terminal_sn',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
